"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "../lib/auth/providers";
import i18n from "@/locales/i18n";
import { I18nextProvider } from "react-i18next";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className={inter.className}>
        <I18nextProvider i18n={i18n}>
          <NextAuthProvider>{children}</NextAuthProvider>
        </I18nextProvider>
      </body>
    </html>
  );
}
